### PR TITLE
udated data for github assignment

### PR DESCRIPTION
**Pull request by BlaizDickson**

### CODE REVIEW

**Review by zizoh — APPROVED** [review]

**Review by antoHero — CHANGES_REQUESTED** [review]
Hello @BlaizDickson, unfortunately your pull request cannot be merged at this time as one criteria for merging is that you work from the repository and not a fork. Kindly clone the project and try again. Well done!

**Comment by BlaizDickson** [comment]
Whenever I try to push my work on github I get this error message " You
don't have permissions to push to 'DanSam5K/class-work' on GitHub. Would
you like to create a fork and push to it instead?" Please help me check and
resolve this issue.

**Comment by BlaizDickson** [comment]
https://github.com/BlaizDickson/RockPaperScissors-Project/pull/1

**Comment by BlaizDickson** [comment]
Good day sir.
Here is another PR
https://github.com/BlaizDickson/RockPaperScissors-Project/pull/2 with the
changes as observed by you from the previous PR.

**Comment by BlaizDickson** [comment]
PLEASE I NEED REVIEW FOR THIS PR BELOW
https://github.com/BlaizDickson/my_portfoilio/pull/1

**Pull request closed without merging**
