### PR TITLE
Dixon's assignment 1

### PR DESCRIPTION
**Pull request by BlaizDickson**
Dixon's first assignment

### CODE REVIEW

**Comment by zizoh** [comment]
Great job on your first PR! 🎉

The commit message/PR title can be a bit more specific so that other people can know what you did. It can be something like "Add personal info to data file". It may also be helpful to check previous PRs for guidance.

**Review by zizoh — APPROVED** [review]

**Review by antoHero — APPROVED** [review]
Good job on opening your first PR but like @zizoh suggested it can be more descriptive.

**Review by Phildeoner — APPROVED** [review]
Weldone and happy coding

**Review by DanSam5K — APPROVED** [review]
## Hi @BlaizDickson, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by BlaizDickson** [comment]
> ## Hi @BlaizDickson,
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! tada
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Thanks for the review.

**Pull request merged**
